#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Kill if already running
killall -9 xfsettingsd picom polybar dunst ksuperkey xfce4-power-manager

if [[ $(xrandr -q | grep 'DP-1-0 connected') ]]; then
    xrandr --output eDP1 --mode 1920x1080 -r 144.03 --rotate normal --output DP-1-0 --primary --mode 1920x1080 -r 164.5 --rotate normal --left-of eDP1
fi

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

sleep 2

## Start Compositing Manager
exec picom &

## Launch Polybar
bash ~/.config/openbox/polybar/launch.sh

## Notification Daemon
exec dunst &

## Launch Plank
exec plank &

## Pacmanfm
exec pcmanfm -d &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

